### PR TITLE
update a few of the examples to use better code

### PR DESCRIPTION
**Pull request by Swishilicous**
too lazy to update any of the others but these examples bugged me so i made them in a more readable coding style imo

### CODE REVIEW

**Comment by 13-05** [comment]
lol as soon as i transfer the repo it gets a PR

**Comment by Swishilicous** [comment]
> lol as soon as i transfer the repo it gets a PR

just happened to see u talk abt this project in pc server when u said u were giving up on maintaining and thought i'd check it out

**Comment by 13-05** [comment]
ah okay

it seems doggybootsy hasnt merged this - i can do that rq, i checked out your changes and they seem reasonable

**Comment by 13-05** [comment]
probably my last big action on this repo

**Pull request merged**
