### PR TITLE
getModule fix

### PR DESCRIPTION
**Pull request by tungdo0602**

### CODE REVIEW

**Comment by tungdo0602** [comment]
rewrite

**Comment by Bettlee** [comment]
What about, `ZP`?

**Comment by tungdo0602** [comment]
> What about, `ZP`?

oh i forgot

**Comment by Bettlee** [comment]
Also, I've written a script of my own: [getModule.js](https://gist.github.com/Bettlee/a729de177fcaa4c3b7d5ceef0aa618dc)

**Pull request closed without merging**
